### ISSUE TITLE
practica de operaciones basicas

### ISSUE THREAD

**Issue by W1ll1am21** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-W1ll1am21#1]
[practica sistemas numericos.pdf](https://github.com/user-attachments/files/16845124/practica.sistemas.numericos.pdf)

**Comment by QUET012** [comment]
Portada:24/25
Procedimiento:25/25
Figuras ilustraciones y fotografias :25/25
Resultados y conclusiones:24/25
Calificacion final:19.6

**Comment by josealfredo79** [comment]
bien hecho y revisado..
